### ISSUE TITLE
'np.int' Deprecated

### ISSUE THREAD

**Issue by alekthegenius** [YatingMusic/miditoolkit#25]
I get an error using the latest version of Num1Py (Version: 1.25.1) because it appears miditoolkit is using the attribute 'np.int', which was deprecated in NumPy 1.2 and eventually removed in 1.24.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alek/.local/lib/python3.10/site-packages/miditoolkit/midi/parser.py", line 66, in __init__
    self.instruments = self._load_instruments(mido_obj)
  File "/home/alek/.local/lib/python3.10/site-packages/miditoolkit/midi/parser.py", line 205, in _load_instruments
    current_instrument = np.zeros(16, dtype=np.int)
  File "/home/alek/.local/lib/python3.10/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

This is on a fresh conda environment with NumPy 1.25.1, miditoolkit 0.1.16, and Python 3.10.12

**Comment by Natooz** [comment]
Closing this as it is now fixed in v1.0.0
`pip install -U miditoolkit`
